"use client";

import { NumberField } from "../shared/number-field";
import type { RoasInput } from "./schema";

type RoasFormProps = {
  value: RoasInput;
  onChange: (nextValue: RoasInput) => void;
};

export function RoasForm({ value, onChange }: RoasFormProps) {
  return (
    <form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => event.preventDefault()}>
      <NumberField label="Ad spend" value={value.adSpend} onChange={(adSpend) => onChange({ ...value, adSpend })} placeholder="1200" helpText="Amount spent on advertising." />
      <NumberField label="Revenue" value={value.revenue} onChange={(revenue) => onChange({ ...value, revenue })} placeholder="5400" helpText="Revenue generated by those ads." />
    </form>
  );
}